# Generated by Django 3.0.3 on 2020-02-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200211_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user_id',
        ),
    ]
